---
# tasks file for common

- name: 'Add common users'
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "/bin/bash"
  loop: "{{ common_users }}"

- name: 'Add common users ssh keys'
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  when: item.ssh_key
  loop: "{{ common_users }}"

- name: 'Add admin users sudoers files'
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ item.name }}"
    content: "{{ item.name }}  ALL=(ALL)  NOPASSWD: ALL"
    owner: root
    group: root
    mode: '0600'
  when: item.admin
  loop: "{{ common_users }}"
