---
dependency:
  name: galaxy
  command: 'apt-get update && apt install python3 -y'
driver:
  name: docker
platforms:
  - name: Ubuntu
    image: ubuntu:20.04
    pre_build_image: false

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: group_vars/

    
verifier:
  name: testinfra
  directory: tests/
lint: |
  set -e
  yamllint .
  ansible-lint .
